apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: alerting-platform-ingress
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: "alerting-platform-backend-ip"
spec:
  rules:
    - http:
        paths:
          - path: /api/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: alerting-platform-api
                port:
                  number: {{ .Values.env.API_PORT }}
