apiVersion: v1
kind: Service
metadata:
  name: alerting-platform-api
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: ClusterIP
  selector:
    app: alerting-platform-api
  ports:
    - port: {{ .Values.env.API_PORT }}
      targetPort: {{ .Values.env.API_PORT }}
